name: xkyber_crypto
description: A library for post-quantum cryptography using the Kyber algorithm as base.
version: 1.0.7
homepage: https://github.com/xscriptorcode/xkyber_crypto
repository: https://github.com/xscriptorcode/xkyber_crypto
issue_tracker: https://github.com/xscriptorcode/xkyber_crypto/issues

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  collection: ^1.19.1
  crypto: ^3.0.6
  pointycastle: ^3.9.1
  lints: ^5.0.0
  cryptography: ^2.7.0
  fixnum: ^1.1.1


dev_dependencies:
  test: ^1.16.0
  
  


# Etiquetas
topics:
  - security
  - kyber-algotihm
  - dart
  - post-quantum-cryptography
  - data-protection
  