name: xkyber_crypto
description: Una implementación de Kyber derivada de X para cifrado post-cuántico en Dart.
version: 1.0.0
homepage: https://github.com/xscriptorcode/xkyber_crypto
repository: https://github.com/xscriptorcode/xkyber_crypto
environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  crypto: ^3.0.0
  pointycastle: ^3.5.0
  lints: ^2.0.0

dev_dependencies:
  test: ^1.16.0

# Información adicional
issue_tracker: https://github.com/xscriptorcode/xkyber_crypto/issues

# Etiquetas
topics:
  - crypto
  - kyber
  - dart
  - post-quantum
